spring:
  application:
    name: review
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000 # 5 seconds
          max-interval: 300000 # 300 seconds
          multiplier: 2

server:
  port: ${REVIEW_PORT:0}
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}